name: Supla MQTT Autodiscovery
version: "1.0.6-patched2"
slug: supla_autodiscovery
description: "Automatyczne generowanie autodiscovery dla danych Supla MQTT"
arch:
  - aarch64
startup: services
boot: auto
init: false

options:
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_username: "marhoi"
  mqtt_password: "3151"
  tls: false
  ca_certs: ""
  supla_prefix: "supla"
  discovery_prefix: "homeassistant"
  name_prefix: "Supla"
  include_devices: []
  exclude_devices: []
  publish_interval: 0

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  tls: bool
  ca_certs: str?
  supla_prefix: str
  discovery_prefix: str
  name_prefix: str
  include_devices:
    - int
  exclude_devices:
    - int
  publish_interval: int
