name: Supla MQTT Autodiscovery
version: "1.1.0-alpha"
slug: supla_autodiscovery
description: "Automatyczne generowanie autodiscovery dla danych Supla MQTT"
arch:
  - aarch64
startup: services
boot: auto
init: false
map:
  - config:rw
  - ssl:ro
services:
  - mqtt:need

options:
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_username: "marhoi"
  mqtt_password: "3151"
  tls: false
  ca_certs: ""
  supla_prefix: "supla"
  discovery_prefix: "homeassistant"
  name_prefix: "Supla"
  qos: 0
  retain: true
  include_devices:
    - 2995
    - 6912
    - 6913
    - 7389
  exclude_devices: []
  publish_interval: 0

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  tls: bool
  ca_certs: str?
  supla_prefix: str
  discovery_prefix: str
  name_prefix: str
  qos: int?
  retain: bool?
  include_devices:
    - int?
  exclude_devices:
    - int?
  publish_interval: int?
